### ISSUE TITLE
Couldn't resolve host

### ISSUE THREAD

**Issue by stevukas** [davidtsadler/ebay-sdk-php#6] opened 2015-10-26 15:32 UTC
Hello,
Thanks for the great SDK
Recently, we are getting too many curl error
Couldn't resolve host 'api.ebay.com' [url] https://api.ebay.com/ws/api.dll'
before was everything is ok, it was very rare, but now we are getting it a lot
how we could solve such issue?
thanks again

**Comment by michabbb** [comment] 2015-10-30 14:23
hi, we noticed the same error very often too, and till today i am not 100% sure if the problem is the DNS or not. but my try and error will be to put the IP/hostname into the /etc/hosts....

**Comment by davidtsadler** [comment] 2016-01-20 15:52
Closing this for now. Please add more information if this issue is still occurring for you.

**Closed by davidtsadler** 2016-01-20 15:52 UTC
