### ISSUE TITLE
Setting Delivery to Free - Add Fixed Price Item (or any item)

### ISSUE THREAD

**Issue by AndrewMarkMedia** [davidtsadler/ebay-sdk-php#118] opened 2017-06-22 18:24 UTC
I wonder if anyone can point me in the right direction on this one. I have searched through docs to no avail. I apologies if I have missed something.

I am able to list a fixed priced item if there is shipping set up with a charge, but I am trying to make it so that the shipping is free, with the code below...

$item->ShippingDetails = new Types\ShippingDetailsType();
$item->ShippingDetails->ShippingType = Enums\ShippingTypeCodeType::C_FREE;

$shippingService = new Types\ShippingServiceOptionsType();
$shippingService->ShippingServicePriority = 1;
$shippingService->ShippingService = 'UK_RoyalMailFirstClassRecorded';
$shippingService->ShippingServiceCost = new Types\AmountType(['value' => 0.00]);
$shippingService->ShippingServiceAdditionalCost = new Types\AmountType(['value' => 0.00]);
$item->ShippingDetails->ShippingServiceOptions[] = $shippingService;

I am obviously doing something wrong here (and probably really silly), but my head won't take anymore bashing against the wall.

Any hint will do.

Thank you

**Comment by michabbb** [comment] 2017-06-22 18:35
as far as i know, the whole shipping stuff should be managed via [Policies.](http://sellercentre.ebay.com.au/ebay-for-business/business-policies) 
there for you can [login](http://www.bizpolicy.ebay.co.uk/businesspolicy/manage) into ebay to manage these, if your account has activated them. for my very personal opinion, working with these policies is very easy, as long as you don´t have a too complex shipping structure (i.e. different shipping costs for every single item). 

a shipping policy handles every detail of your shipping options, so instead of using 30 parameters in your call, you just only set one single parameter:  [ShippingProfileID](http://developer.ebay.com/devzone/xml/docs/reference/ebay/additem.html#Request.Item.SellerProfiles.SellerShippingProfile.ShippingProfileID)

if you don´t use business policies, maybe [FreeShipping](http://developer.ebay.com/devzone/xml/docs/reference/ebay/additem.html#Request.Item.ShippingDetails.ShippingServiceOptions.FreeShipping) is the missing key in your case.

**Comment by AndrewMarkMedia** [comment] 2017-06-22 20:51
Thank you foe the reply. That kind of dows make sense.

With reference then to the variables ShippingProfileID and FreeShipping, are theae referenced in some way...in this sdk?

Thanks again for the reply.

**Comment by michabbb** [comment] 2017-06-22 21:20
the SDK is build of ebay´s WSDL, so of course you will find every "property" in the SDK

- [ShippingProfileID](https://github.com/davidtsadler/ebay-sdk-php/blob/3584f5fa985386b392b178d1b4212b6770dbc547/src/Trading/Types/SellerShippingProfileType.php#L15)
- [FreeShipping](https://github.com/davidtsadler/ebay-sdk-php/blob/3584f5fa985386b392b178d1b4212b6770dbc547/src/Trading/Types/ShippingServiceOptionsType.php#L24)

**Comment by davidtsadler** [comment] 2017-06-23 16:14
Closing as it's not a bug with the SDK. 

Help with the SDK can be found in [Forum](https://forum.devbay.net/c/php-sdk) or [Google Group](https://groups.google.com/forum/?hl=en#!forum/ebay-sdk-php).

**Closed by davidtsadler** 2017-06-23 16:14 UTC
