### ISSUE TITLE
eBay updated Fulfillment endpoint to 1.2.0

### ISSUE THREAD

**Issue by chuhta** [davidtsadler/ebay-sdk-php#111] opened 2017-06-14 14:11 UTC
The `GetOrders` and `GetOrder` calls now blow up with an undefined property after eBay updated their fulfillment endpoint to 1.2.0.

This added a new `lineItemFulfillmentInstructions` to the order's data that the response is not expecting.

http://developer.ebay.com/devzone/rest/sell/content/fulfillment/release-notes.html

**Comment by parts-rescue** [comment] 2017-06-14 14:16
I can confirm that I ran into the same issue this morning after using the same script for over a month.

**Comment by davidtsadler** [comment] 2017-06-14 14:56
Cheers for letting me know. I'll bring the SDK up to date with eBay's API changes.

**Comment by davidtsadler** [comment] 2017-06-14 15:24
Looks like this issue will be resolved by the commit https://github.com/davidtsadler/ebay-sdk-php/commit/47d312c135e19c4b39c451957396a9f785d355f4.

I'll close this issue once the changes have been merged from the develop branch into the main.

**Comment by chuhta** [comment] 2017-06-14 19:09
Is there an ETA on when the currently unreleased version will be merged?

**Comment by parts-rescue** [comment] 2017-06-14 19:12
> Is there an ETA on when the currently unreleased version will be merged?

I was just going to close the development version for the time being.  That would work, right?

**Comment by davidtsadler** [comment] 2017-06-15 12:21
There is now a 12.0.1 release that will ignore unknown properties in the JSON response. 

I will keep this issue open as the missing properties will be added to the SDK when I next merge the develop branch. Because there are a lot of changes coming from that branch I don't want those changes going across just yet, hence the 12.0.1 release.

**Comment by chuhta** [comment] 2017-06-15 15:18
Looks like 12.0.1 handled the pressing issue of the endpoint not working anymore. Thanks for the prompt response.

**Comment by parts-rescue** [comment] 2017-06-15 23:02
Thanks David!    Working great for me as well.

**Comment by davidtsadler** [comment] 2017-06-23 15:58
The missing properties have been added with the 13.0.0 release.

**Closed by davidtsadler** 2017-06-23 15:58 UTC
Labels: enhancement
