### ISSUE TITLE
NoResults for Fulfillment: GetOrders with filter:orderfulfillmentstatus

### ISSUE THREAD

**Issue by alka-git** [davidtsadler/ebay-sdk-php#77] opened 2017-03-09 15:01 UTC
How can i use "orderfulfillmentstatus" filter? My response is empty! No errors, but no results too. If i use API-Explorer from eBay, the response is empty too! If i use GetAnOrder by orderId, i get the right order.

**Comment by davidtsadler** [comment] 2017-06-23 16:14
Closing as it's not a bug with the SDK. 

Help with the SDK can be found in [Forum](https://forum.devbay.net/c/php-sdk) or [Google Group](https://groups.google.com/forum/?hl=en#!forum/ebay-sdk-php).

**Closed by davidtsadler** 2017-06-23 16:14 UTC
