### ISSUE TITLE
The GetMyeBaySelling request cant response PictureDetails of items..

### ISSUE THREAD

**Issue by slaveykov** [davidtsadler/ebay-sdk-php#117] opened 2017-06-21 12:48 UTC
The GetMyeBaySelling request cant response PictureDetails of items. Why?

**Comment by davidtsadler** [comment] 2017-06-23 16:14
Closing as it's not a bug with the SDK. 

Help with the SDK can be found in [Forum](https://forum.devbay.net/c/php-sdk) or [Google Group](https://groups.google.com/forum/?hl=en#!forum/ebay-sdk-php).

**Closed by davidtsadler** 2017-06-23 16:14 UTC
